language: c
sudo: false
os: linux

cache:
  directories:
    - $HOME/gcc-arm-none-eabi-7-2018-q2-update

install:
  - export GCC_DIR=$HOME/gcc-arm-none-eabi-7-2018-q2-update
  - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
  - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2?revision=bc2c96c0-14b5-4bb4-9f18-bceb4050fee7?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2018-q2-update
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
  - export PATH=$PATH:$GCC_DIR/bin

script:
  - cd Firmware
  - make
